### ISSUE TITLE
I have Libcurl, but not debrid.sh

### ISSUE THREAD

**Issue by OhWowOffice** [manuGMG/debrid-scripts#3]
I think I am confused by your directions, you say that to use this you will need a C version of Debrid.sh which is Libcurl, but after downloading Libcurl I do not have debrid.sh as a file or directory.

Sorry if this doesn't directly relate to the script, I summited this issue because it's the next best thing to a DM.

**Comment by manuGMG** [comment]
That was a typo (now fixed), `debrid.c` is just another script. `libcurl` is needed to compile it.
